### Lista usuários
GET http://localhost:3000/users


### Cadastra novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
    "nome": "John Doe",
    "email": "test2@email.com",
    "dataNascimento": "21/01/2009",
    "password": "Gg123@45"
}